import './globals.css';
import { Poppins, Nunito, Josefin_Sans } from 'next/font/google';
import Header from '../components/layout/Header';
import Navigation from '@/components/layout/Navigation';
import Footer from '../components/layout/Footer';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

// Define fonts
const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

const nunito = Nunito({
  weight: ['300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

const josefin = Josefin_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${poppins.className} ${nunito.className} ${josefin.className}`}
    >
      <body>
        <Navigation />
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
