import './globals.css';
import { Poppins } from 'next/font/google';
import Header from '../components/layout/Header';
import Hero from '../components/layout/HeroCarousel';
import Footer from '../components/layout/Footer';

export const metadata = {
  title: 'Suits 20/20',
  description: 'Generated by Next.js',
};

// Define fonts
const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.className}`}>
      <body>
        <Header />
        <Hero />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
